config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :contacts
  end
  resources :sessions
  resources :groups
  match '/login',    to: 'sessions#new',         via: 'get'
  match '/',         to: 'sessions#index',       via: 'get'
  match '/signout',  to: 'sessions#destroy',     via: 'delete'
  match '/delete_account', to: 'users#delete_account', via: 'get'
  match '/delete_confirmed', to: 'users#delete_confirmed', via: 'post'
  match '/delete_group',  to: 'contacts#delete_group',  via: 'get'
  match '/remove_group_member', to: 'contacts#remove_group_member', via: 'get'
  match '/change_password', to: 'users#change_password_form', via: 'get'
  match '/change_password_confirm', to: 'users#change_password', via: 'patch'
  match '/add_group_member', to: 'contacts#add_group_member_list_show', via: 'get'
  match '/add_member_process', to: 'contacts#add_group_member', via: 'get'
  match '/add_group', to: 'groups#add_group', via: 'get'
  match '/add_new_group_member', to: 'contacts#add_new_group_contact', via: 'post'
  match '/Thank_You', to: 'groups#thank_you', via: 'get'
  match '/unsubscribe', to: 'groups#unsubscribe', via: 'get' 
  match '/unsubscribe_from', to: 'groups#unsubscribe_post', via: 'get'
  match '/unsubscribe', to: 'groups#unsubscribe_delete', via: 'delete'  


  root 'sessions#index'








end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def new
		@user = User.find(params[:id])
		@groupname = params[:group_name]
	end
	
	def show
		if signed_in?
			@user = current_user
			@viewname = params[:group_name]
			split_name = @viewname.split(" ")
			@url_name = split_name.join("+")	
		else
			redirect_to root_url
		end
	end

	def index
		if signed_in?
			@user = current_user
			@row_iterator = @user.contacts.select('DISTINCT group_name')
		else
			redirect_to root_url
		end
	end

	def add_group
		if signed_in?
			@user = current_user
		else
			redirect_to root_url
		end
	end

	def unsubscribe
		@user = User.find(params[:id])
	end

	def unsubscribe_post
		@user = User.find(params[:id])
		@email = params[:email]
		@subscriptions = Contact.where("email = '#{@email}' AND user_id = '#{@user.id}'")
		@name = @subscriptions[0].name

	end

	def unsubscribe_delete
		@user = User.find(params[:id])
		@email = params[:email]
		@group_name = params[:group_name]
		@contact = Contact.where("email = '#{@email}' AND group_name = '#{@group_name}'")
		Contact.find(@contact[0][:id]).destroy
		redirect_to unsubscribe_from_path(id: @user.id, email: @email)

	end

	def thank_you
		
	end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/add_group.html.erb
<% provide(:title, "Create A New Group") %>
<h1>Create A New Group</h1>
<br>
<br>
<br>
<div class="center hero-unit">
	Enter New Group Name
	<br>
	<br>
	<%= form_tag add_group_member_path(@user), method: :get do %>
		<%= text_field_tag :group_name %>
		<br>
		<br>
		<%= submit_tag 'Create group', class: "btn btn-small btn-primary" %>
	<% end %>
	<br>
	(You will need to add at least one contact to the group in order to save the group)
</div>

app/views/groups/index.html.erb
<% provide(:title, 'View Groups') %>
<% @OutputName = [] %>
<% @OutputName = @user.name.split(" ") %>
<h1><%= "#{@OutputName[0]}'s" %> Groups</h1>
<br>
<br>
<div class="center hero-unit">
	<table align="center">
		<col>
		<col width="25">
		<col>
		<col width="25">
		<col>
		<col width="25">
		<col>
		<tr>
			<th>Group name</th>	
		</tr>
		<% @row_iterator.each do |row| %>
	     	<tr>
	     		<td>
			     	<% if row.group_name == "default" %>
						All Contacts
					<% else %>
						<%= row.group_name %>
					<% end %>
		        </td>
		        <td></td>
		        <td>
		        	<%= link_to 'View Group', group_path(id: @user.id, group_name: row.group_name), class: "btn btn-small btn-primary" %>
		        </td>
		       <% if row.group_name != "default" %>
			        <td></td>
			        <td>
			        	<%= link_to 'Delete group', delete_group_path(user_id: @user.id, id: @group_locator), class: "btn btn-small btn-primary" %>
			        </td>
				<% end %>
			</tr>
		<% end %>
	</table>
	<br>
</div>
<%= link_to 'Create new Group', add_group_path(@user), class: "btn btn-med btn-primary" %>

app/views/groups/new.html.erb
<% provide(:title, 'New Group Contact') %>
<title>New group</title>
<% if signed_in? %>
	<h1>Create New Contact For <%= "#{@groupname}" %> Group</h1>
	<br>
<%else%>
	<h1>Join The Contact List For <%= "#{@groupname}" %> Group</h1>
<% end %>
<br>
<br>
<div class="center hero-unit">
	<%= form_for :contact, url: add_new_group_member_path(id: @user.id) do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name %>
		<br>
		<%= f.label :email %>
		<%= f.text_field :email %>
		
		<%= f.hidden_field :group_name, value: @groupname %>

		<br>
		<% if signed_in? %>
			<%= f.submit "Create contact", class: "btn btn-small btn-primary" %>
		<% else %>
			<br>
			<%= f.check_box :agree, {}, true, false %>
			<font class="terms_conditions">Tick here if you do not want to be sent other information from this source</font>
			<br>
			<%= f.submit "Join group", class: "btn btn-small btn-primary" %>
		<% end %>
	<% end %>
</div>
<% if signed_in? %>
	<div align="center">
		<table>
			<col>
			<col width="50">
			<col>
			<tr>
				<td><%= link_to 'Add contact to group', add_group_member_path(@user, group_name: @groupname), class: "btn btn-small btn-primary" %></td>
				<td></td>
				<td><%= link_to 'Back to group', group_path(id: @user.id, group_name: @groupname), class: "btn btn-small btn-primary" %></td>
			</tr>
		</table>
	</div>
<% end %>

app/views/groups/show.html.erb
<% provide(:title, "#{@viewname} Members") %>
<% if @viewname == "default" %>
	<h1>Showing All Contacts</h1>
<% else %>
	<h1>Members of <%= @viewname %> Group</h1>
<% end %>
<br>
<div align="right">
	<%= link_to "Back to groups", groups_path(@user), class: "btn btn-small btn-primary" %>
</div>
<br>
<% @email_list = [] %>
<div class="center hero-unit">

	<table align="center">
		<col>
		<col width="25">
  		<col>
		<tr>
		    <th>Contact name</th>
		    <th></th>
		    <th>Contact email address</th>
		</tr>
		<% @user.contacts.each do |contact| %>
			<% if contact.group_name == @viewname %>
				<tr>
			    	<td><%= contact.name %></td>
			    	<td></td>
			    	<td><%= contact.email %></td>
			    	<td><%= link_to 'Remove from group', remove_group_member_path(user_id: @user.id, id: contact.id), data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-primary" %></td>
			  	</tr>
				<% @group_locator = contact.id %>
				<% @email_list.push(contact.email) %>
		    <% end %>
		<% end %>
	</table>
	<br>
	<br>
</div>
<% if @viewname != "default" %>
	<br>
	<br>
	URL to direct user to add themselves to this group :- <font color="blue">http://methods-mail.herokuapp.com/groups/new?group_name=<%= @url_name %>&id=<%= @user.id %></font>
<% end %>
<br>
<br>
<br>
<table align="center">
	<col>
	<col width="25">
	<col>
	<col width="25">
	<col>
	<col width="25">
	<col>
	<% if @viewname == "default" %>
		<tr>
			<td>
				<%= link_to "New Contact", new_user_contact_path(@user), class: "btn btn-med btn-primary" %>
			</td>
			<td></td>
			<td>
				<a href="mailto:<% @email_list.each do |address| %><%= address %>;%20<% end %>?Subject=<%= @viewname %>%20-%20" target="_top" class="btn btn-primary">Send E-Mail <span class="glyphicon glyphicon-envelope"></span></a>
			</td>
		</tr>
	<% else %>
		<tr>
	    	<td><%= link_to 'Add contact to group', add_group_member_path(group_name: @viewname), class: "btn btn-med btn-primary" %></td>
	    	<td></td>
	    	<td><%= link_to 'New contact', new_group_path(id: @user.id, group_name: @viewname), class: "btn btn-med btn-primary" %></td>
	    	<td></td>
	    	<td>
				<a href="mailto:<% @email_list.each do |address| %><%= address %>;%20<% end %>?Subject=<%= @viewname %>%20-%20" target="_top" class="btn btn-primary">Send E-Mail <span class="glyphicon glyphicon-envelope"></span></a>
			</td>
	    	<td></td>
	    	<td><%= link_to 'Delete group', delete_group_path(user_id: @user.id, id: @group_locator), class: "btn btn-med btn-primary" %></td>
	  	</tr>
  	<% end %>
</table>



app/views/groups/thank_you.html.erb
<br>
<h1>Thank You</h1>
<br>
<h3>Your details have been added to the mailing list</h3>

app/views/groups/unsubscribe.html.erb
<h2>Unsubscribe from mailing lists from <br>
	<%= @user.name %></h2>
	<br>
<% provide(:title, 'Unsubscribe from a mailing list') %>
	<%= form_tag("/unsubscribe_from?id=#{@user.id}", method: "get") do %>
	<%= label_tag(:email, "Enter your Email:") %>
	<%= text_field_tag(:email) %>
	<%= hidden_field_tag(:id, @user.id) %>
	<br>
	<%= submit_tag("Show subscriptions", class:"btn btn-primary") %>

<% end %>

app/views/groups/unsubscribe_delete.html.erb
<%= @email %> has been removed from
<%= @contact[0][:group_name] %>


<br><%= form_tag("/unsubscribe_from?email=#{@email}", method: "post") do %>
		
		<%= hidden_field_tag(:email,  @email) %>
		<%= submit_tag("Back to your subscriptions") %>
		
	<% end %>

app/views/groups/unsubscribe_post.html.erb
<h3><strong>Hello <%= @name %></strong></h3>
<br>
Your current subscriptions with <%= @user.name %>:
<!-- http://localhost:3000/groups/new?group_name=Kanes+friends&id=1 -->
<br>
<br>
<table align="center">
	<col>
	<col width="25">
		<col>
	<% @subscriptions.each do |s| %>
		<%= form_tag("/unsubscribe?email=#{@email}", method: "delete") do %>
			<tr>
				<% if s[:group_name] == "default" %>
					<td><%= label_tag(:groupname, "General Contacts") %></td>
				<% else %>
			    	<td><%= label_tag(:groupname, "#{s[:group_name]}") %></td>
			    <% end %>
		    	<td><%= hidden_field_tag(:group_name,  s[:group_name]) %></td>
		    	<td><%= hidden_field_tag(:id,  @user.id) %></td>
		    	<td><%= submit_tag("Delete subscription", class: "btn btn-small btn-primary") %></td>
		  	</tr>
	    <% end %>
	<% end %>
</table>