config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :contacts
  end
  resources :sessions
  resources :groups
  match '/login',    to: 'sessions#new',         via: 'get'
  match '/',         to: 'sessions#index',       via: 'get'
  match '/signout',  to: 'sessions#destroy',     via: 'delete'
  match '/delete_account', to: 'users#delete_account', via: 'get'
  match '/delete_confirmed', to: 'users#delete_confirmed', via: 'post'
  match '/delete_group',  to: 'contacts#delete_group',  via: 'get'
  match '/remove_group_member', to: 'contacts#remove_group_member', via: 'get'
  match '/change_password', to: 'users#change_password_form', via: 'get'
  match '/change_password_confirm', to: 'users#change_password', via: 'patch'
  match '/add_group_member', to: 'contacts#add_group_member_list_show', via: 'get'
  match '/add_member_process', to: 'contacts#add_group_member', via: 'get'
  match '/add_group', to: 'groups#add_group', via: 'get'
  match '/add_new_group_member', to: 'contacts#add_new_group_contact', via: 'post'
  match '/Thank_You', to: 'groups#thank_you', via: 'get'
  match '/unsubscribe', to: 'groups#unsubscribe', via: 'get' 
  match '/unsubscribe_from', to: 'groups#unsubscribe_post', via: 'get'
  match '/unsubscribe', to: 'groups#unsubscribe_delete', via: 'delete'  


  root 'sessions#index'








end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :contacts, dependent: :destroy


	before_save {self.email = email.downcase}
	before_create :create_remember_token

	has_secure_password
	validates :password, length: {minimum: 6}

	def User.create_secure_password(user_params)
		has_secure_password(user_params)
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private 
	def create_remember_token
		self.remember_token = User.digest(User.new_remember_token)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new

  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in(@user)
      flash[:success] = "Account created successfully"
  		redirect_to user_path(@user)
  	else
      flash.now[:error] = "Failed to create account"
  		render 'new'
  	end
  end

  def show
    if signed_in?
    	@user = User.find(params[:id])

    else
      redirect_to root_url
    end
  end

  def delete_account
    if signed_in?
      @user = User.find(params[:id])
    else
      redirect_to root_url
    end
  end

  def delete_confirmed
    if signed_in?
      @user = User.find(params[:id])
      if @user && @user.authenticate(params[:user][:password])
        sign_out
        @user.destroy
        flash[:success] = "Account successfully deleted"
        redirect_to root_url
      else
        flash.now[:error] = "Incorrect password entered"
        render 'delete_account'
      end
    else
      redirect_to root_url
    end
  end

  def edit
    if signed_in?
      @user = User.find(params[:id])
    else
      redirect_to root_url
    end
  end

  def update
    if signed_in?
      @user = current_user
      @new_name = (user_params[:name])
      @new_email = (user_params[:email])
      if @user && @user.authenticate(params[:user][:password])
        if User.find(@user.id).update_attribute(:email, @new_email) && User.find(@user.id).update_attribute(:name, @new_name)
          redirect_to root_url 
          flash[:success] = "Account details successfully updated" 
        else
          flash.now[:error] = "Failed to update account details"
          render 'edit'
        end
      else
        flash.now[:error] = "Incorrect password entered"
        render 'edit'
      end
    else
      redirect_to root_url
    end
  end

  def change_password_form
    if signed_in?
      @user = current_user
    else
      redirect_to root_url
    end
  end

  def change_password
    if signed_in?
      @user = current_user
      @new_password = (params[:user][:password])
      @old_password = (user_params[:old_password])
      @confirm_password = (user_params[:password_confirmation])
      @update_user = User.new(name: @user.name, email: @user.email, password: @new_password, password_confirmation: @confirm_password)
      if @user && @user.authenticate(params[:user][:old_password])
        @update_user.save
        if @user.update_attribute(:password_digest, @update_user.password_digest)
          flash[:success] = "Password successfully changed"
          redirect_to root_url
        else
          flash[:error] = "Password change failed"
          render 'change_password_form'
        end
        @update_user.destroy
      else
        flash[:error] = "Incorrect password entered"
        render 'change_password_form'
      end
    else
      redirect_to root_url
    end
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation, :old_password)
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/change_password_form.html.erb
<% provide(:title, 'Change password') %>
<h1>Change password</h1>
<br>
<br>
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<br>
<div class="center hero-unit">
	<%= form_for :user, url: change_password_confirm_path(id: @user.id), method: :patch do |f| %>

		<%= f.label "Current password" %>
		<%= f.password_field :old_password %>
		<br>
		<%= f.label "New password" %>
		<%= f.password_field :password %>
		<br>
		<%= f.label "Confirm new password" %>
		<%= f.password_field :password_confirmation %>
		<br>
		<%= f.submit "Change password", class: "btn btn-small btn-primary" %>
	<% end %>
</div>

app/views/users/delete_account.html.erb
<% provide(:title, 'Delete Account') %>
<h1>Delete Account?</h1>
<br>
<br>
<br>
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<br>
<div class="center hero-unit">
	<h4>Please enter your password and confirm you wish to delete your account:</h4>
	<%= form_for :user, url: delete_confirmed_path(id: @user.id) do |f| %>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<br>
		<%= f.submit "Delete Account", class: "btn btn-small btn-primary" %>
	<% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit account details') %>
<h1>Edit account details</h1>
<br>
<br>
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<br>
<div class="center hero-unit">
	<%= form_for :user, url: user_path(id: @user.id), method: :patch do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name %>
		<br>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<br>
		<br>
		<%= f.label "Please confirm your password to update account details"%>
		<%= f.password_field :password %>
		<br>
		<%= f.submit "Update account details", class: "btn btn-small btn-primary" %>
	<% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<title>Sign up</title>
<h1>New User</h1>
<%= form_for :user, url: users_path do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<br>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<br>
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<br>
	<%= f.submit "Create Account", class: "btn btn-small btn-primary" %>

<% end %>

app/views/users/show.html.erb

<% @OutputName = [] %>
<% @OutputName = @user.name.split(" ") %>
<% provide(:title, "#{@OutputName[0]}") %>
<title><%= @user.name %></title>
<h1>Welcome <%= @OutputName[0] %></h1>
<br>
<br>
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<br>
<div class="center hero-unit">
	<h2>Contacts</h2>
	<br>
	<table align="center">
		<col>
		<col width="25">
  		<col>
		<tr>
		    <th>Contact name</th>
		    <th></th>
		    <th>Contact email address</th>
		</tr>
		<% @user.contacts.each do |contact|%>
			<% if contact.group_name == "default" %>
				<tr>
			    	<td><%= contact.name  %></td>
			    	<td></td>
			    	<td><%= contact.email %></td>
			    	<td><%= link_to 'Edit contact details', edit_user_contact_path(user_id: @user.id, id: contact.id), class: "btn btn-small btn-primary" %></td>
			    	<td>
						<a href="mailto:<%= contact.email %>?" target="_top" class="btn btn-small btn-primary">Send E-Mail <span class="glyphicon glyphicon-envelope"></span></a>
					</td>
			    	<td><%= link_to 'Delete contact', user_contact_path(user_id: @user.id, id: contact.id), method: :delete, data: { confirm: 'Are you sure? (This will delete this contact from all groups as well)' }, class: "btn btn-small btn-primary" %></td>
			    </tr>
		    <% end %>
		<% end %>
	</table>
</div>
<br>
<br>

<%= link_to 'View groups', groups_path(@user), class: "btn btn-large btn-primary" %>