config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :contacts
  end
  resources :sessions
  resources :groups
  match '/login',    to: 'sessions#new',         via: 'get'
  match '/',         to: 'sessions#index',       via: 'get'
  match '/signout',  to: 'sessions#destroy',     via: 'delete'
  match '/delete_account', to: 'users#delete_account', via: 'get'
  match '/delete_confirmed', to: 'users#delete_confirmed', via: 'post'
  match '/delete_group',  to: 'contacts#delete_group',  via: 'get'
  match '/remove_group_member', to: 'contacts#remove_group_member', via: 'get'
  match '/change_password', to: 'users#change_password_form', via: 'get'
  match '/change_password_confirm', to: 'users#change_password', via: 'patch'
  match '/add_group_member', to: 'contacts#add_group_member_list_show', via: 'get'
  match '/add_member_process', to: 'contacts#add_group_member', via: 'get'
  match '/add_group', to: 'groups#add_group', via: 'get'
  match '/add_new_group_member', to: 'contacts#add_new_group_contact', via: 'post'
  match '/Thank_You', to: 'groups#thank_you', via: 'get'
  match '/unsubscribe', to: 'groups#unsubscribe', via: 'get' 
  match '/unsubscribe_from', to: 'groups#unsubscribe_post', via: 'get'
  match '/unsubscribe', to: 'groups#unsubscribe_delete', via: 'delete'  


  root 'sessions#index'








end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :user
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  include ContactsHelper
	def new
		if signed_in?
			@user = current_user
			@contact = Contact.new
		else
			redirect_to root_url
		end
	end

	def create
		if signed_in?
			@user = User.find(params[:user_id])
			@contact = @user.contacts.create(contact_params)
			if @contact.group_name.nil?
				@contact.group_name = "default"
			end
			if @contact.save
				redirect_to user_path(@user)
			else
				render 'new'
			end
		else
			redirect_to root_url
		end
	end

	def edit
		if signed_in?
			@user = User.find(params[:user_id])
			@contact = Contact.find(params[:id])
		else
			redirect_to root_url
		end
	end

	def update
		if signed_in?
			@user = User.find(params[:user_id])
			@contact = Contact.find(params[:id])
			@new_name = (contact_params[:name])
			@new_email = (contact_params[:email])
			@contacts = @user.contacts.select('name','email', 'id')
			@update = false
			@contacts.each do |element|
				if element.email == @contact.email
					Contact.find(element.id).update(name: @new_name, email: @new_email)
					@update = true
				end
			end
			if @update
				redirect_to root_url
			else
				flash.now[:error] = "Failed to update contact details"
			    render 'edit'
			end
		else
			redirect_to root_url
		end
	end

	def destroy
		if signed_in?
			@user = User.find(params[:user_id])
			@contact = Contact.find(params[:id])
			@contacts = @user.contacts.select('name','email', 'id')
			@update = "blank"
			@contacts.each do |element|
				if element.email == @contact.email
					Contact.find(element.id).destroy
				end
			end
			redirect_to root_url
		else
			redirect_to root_url
		end
	end

	def delete_group
		if signed_in?
			@user = current_user
			@contact = Contact.find(params[:id])
			@contacts = @user.contacts.select('name','email','id','group_name')
			@output ="blank"
			@contacts.each do |element|
				if element.group_name == @contact.group_name
					Contact.find(element.id).destroy
				end
			end
			redirect_to groups_path(@user)
		else
			redirect_to root_url
		end
	end

	def remove_group_member
		if signed_in?
			@user = current_user
			@contact = Contact.find(params[:id])
			@group_locator = @contact.group_name
			@contact.destroy
			redirect_to group_path(@user, group_name: @group_locator)
		else
			redirect_to root_url
		end
	end

	def add_group_member_list_show
		if signed_in?
			@user = current_user
			@contacts = @user.contacts.all
			@groupname = params[:group_name]
			@non_member_list = generate_non_group_member_list(@contacts, @groupname)
		else
			redirect_to root_url
		end
	end

	def add_group_member
		if signed_in?
			@user = current_user
			@contact = Contact.find(params[:id])
			@group_contact = Contact.new(name: @contact.name, email: @contact.email)
			@group_contact.group_name = params[:group_name]
			@group_contact.user_id = @user.id
			if @group_contact.save
				flash.now[:success] = "Contact added to group"
			else
				flash.now[:error] = "Failed to add contact to group"
			end
			redirect_to add_group_member_path(group_name: @group_contact.group_name)
		else
			redirect_to root_url
		end
	end

	def add_new_group_contact
		@agreed  = contact_params[:agree]
		if @agreed
			@user = User.find(params[:id])
			@group_contact = Contact.new(name: contact_params[:name], email: contact_params[:email],
											group_name: contact_params[:group_name], user_id: @user.id)
			if @group_contact.save
				if signed_in?
					redirect_to user_path(@user)
				else
					redirect_to Thank_You_path(@user)
				end
			else
				render 'groups#new'
			end
		else
			@user = User.find(params[:id])
			@group_contact = @user.contacts.create(contact_params)
			@non_group_contact = @user.contacts.create(contact_params)
			@non_group_contact.group_name = "default"
			if @group_contact.save && @non_group_contact.save
				if signed_in?
					redirect_to user_path(@user)
				else
					redirect_to Thank_You_path(@user)
				end
			else
				render 'groups#new'
			end
		end
	end


	private
		def contact_params
			params.require(:contact).permit(:name, :email, :group_name, :agree)
		end

end

app/helpers/contacts_helper.rb
module ContactsHelper

	def generate_list_of_group_members(allcontacts, groupname)
		groupmemebers = []
		allcontacts.each do |contact|
			if contact.group_name == groupname
				groupmemebers.push(contact.email)
			end
		end
		groupmemebers
	end

	def generate_list_of_all_members(allcontacts)
		contact_list = []
		allcontacts.each do |contact|
			if contact.group_name == "default"
				contact_list.push(contact)
			end
		end
		contact_list
	end

	def generate_non_group_member_list(allcontacts, groupname)
		group_members_list = generate_list_of_group_members(allcontacts, groupname)
		all_contacts_list = generate_list_of_all_members(allcontacts)
		non_member_list = []
		all_contacts_list.each do |contact|
			if !group_members_list.include?(contact.email)
				non_member_list.push(contact)
			end
		end
		non_member_list
	end

end

app/views/contacts/_contact_form.html.erb
<%= form_for :contact, url: user_contacts_path do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<br>
	<% f.text_field :group_name, value: "default" %>
	<%= f.submit "Create contact", class: "btn btn-small btn-primary" %>
<% end %>

app/views/contacts/add_group_member_list_show.html.erb
<% provide(:title, "Add group members") %>
<h1>Add members to <%= @groupname %></h1>
<br>
<br>
<div class="center hero-unit">	
	<% if @non_member_list %>
		<table align="center">
		<col>
		<col width="25">
  		<col>
		<tr>
		    <th>Contact name</th>
		    <th></th>
		    <th>Contact email address</th>
		</tr>
			<% @non_member_list.each do |contact| %>
				<tr>
			    	<td><%= contact.name %></td>
			    	<td></td>
			    	<td><%= contact.email %></td>
			    	<td><%= link_to 'Add to group', add_member_process_path(id: contact.id, group_name: @groupname), class: "btn btn-small btn-primary" %></td>
			  	</tr>
			<% end %>
		</table>
	<% else %>
		<h3>No contacts to add to this group</h3>
	<% end %>	
</div>
<br>
<div align="center">
	<table>
		<col>
		<col width="50">
		<col>
		<tr>
			<td><%= link_to 'New contact', new_group_path(id: @user.id, group_name: @groupname), class: "btn btn-small btn-primary" %></td>
			<td></td>
			<td><%= link_to 'Back to group', group_path(id: @user.id, group_name: @groupname), class: "btn btn-small btn-primary" %></td>
		</tr>
	</table>
</div>

app/views/contacts/edit.html.erb
<% provide(:title, 'Edit contact') %>
<h1>Edit contact details</h1>
<br>
<br>
<br>
<div class="center hero-unit">
	<%= form_for :contact, url: user_contact_path(user_id: @user.id, id: @contact.id), method: :patch do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name %>
		<br>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<br>
		<%= f.submit "Update contact details", class: "btn btn-small btn-primary" %>
	<% end %>
</div>

app/views/contacts/new.html.erb
<% provide(:title, 'New contact') %>
<h1>Create new contact</h1>

<br>
<br>
<br>
<div class="center hero-unit">
	<%= form_for :contact, url: user_contacts_path do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name %>
		<br>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<br>
		<% f.text_field :group_name, value: "default" %>
		<%= f.submit "Create contact", class: "btn btn-small btn-primary" %>
	<% end %>
</div>