config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :contacts
  end
  resources :sessions
  resources :groups
  match '/login',    to: 'sessions#new',         via: 'get'
  match '/',         to: 'sessions#index',       via: 'get'
  match '/signout',  to: 'sessions#destroy',     via: 'delete'
  match '/delete_account', to: 'users#delete_account', via: 'get'
  match '/delete_confirmed', to: 'users#delete_confirmed', via: 'post'
  match '/delete_group',  to: 'contacts#delete_group',  via: 'get'
  match '/remove_group_member', to: 'contacts#remove_group_member', via: 'get'
  match '/change_password', to: 'users#change_password_form', via: 'get'
  match '/change_password_confirm', to: 'users#change_password', via: 'patch'
  match '/add_group_member', to: 'contacts#add_group_member_list_show', via: 'get'
  match '/add_member_process', to: 'contacts#add_group_member', via: 'get'
  match '/add_group', to: 'groups#add_group', via: 'get'
  match '/add_new_group_member', to: 'contacts#add_new_group_contact', via: 'post'
  match '/Thank_You', to: 'groups#thank_you', via: 'get'
  match '/unsubscribe', to: 'groups#unsubscribe', via: 'get' 
  match '/unsubscribe_from', to: 'groups#unsubscribe_post', via: 'get'
  match '/unsubscribe', to: 'groups#unsubscribe_delete', via: 'delete'  


  root 'sessions#index'








end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   <%=image_tag("digital_logo.jpg",alt: "Methods Digital", width: "40")%>
   <i>Life in teal</i>
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        

          <div class="nav-collapse collapse">
            <% if signed_in? %>
              <a href="#" class="brand">Methods Mail</a>
            <% else %>
            <ul class="nav">
              <li class="brand"><%= link_to "Methods Mail", root_path %></li>
            </ul>
            <% end %>
            <ul class="nav pull-right">
            <% if signed_in? %>
              <li><%= link_to "Home", current_user %></li>
              <li><%= link_to "New Contact", new_user_contact_path(@user) %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Groups<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "View Groups", groups_path(@user) %></li>
                  <li><%= link_to "Create New Group", add_group_path(@user) %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Edit account details", edit_user_path(@user) %></li>
                  <li><%= link_to "Change password", change_password_path(@user) %></li>
                  <li><%= link_to 'Delete Account', delete_account_path(id: @user.id) %></a></li>
                </ul>
              </li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
            <% else %>
              <!-- /.add in ability to add yourself to a mailing list  -->
              <li><%= link_to "Log in", login_path %></li>
              <li><%= link_to "Register", new_user_path %></li>
            <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html land="en">
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% if !signed_in? %>
      <div class="container">
        <div class="center hero-unit">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <div class="container">
        <div class="center">
          <%= yield %>
        </div>
      </div>
    <% end %>
    
  </body>
  <%= render 'layouts/footer' %>
</html>